using FraminghamRisk.Domain;

namespace FraminghamRisk.Api.Ai;

// Source is "ai" when generated by the model, "fallback" when generated locally.
public record Explanation(string Summary, IReadOnlyList<string> Suggestions, string Source);

public interface IRiskExplainer
{
    Task<Explanation> ExplainAsync(PatientInput input, RiskResult result, CancellationToken ct = default);
}
