using FraminghamRisk.Domain;

namespace FraminghamRisk.Api.Ai;

/// <summary>A plain-language explanation of a risk result, plus lifestyle suggestions.</summary>
/// <param name="Source">"ai" when generated by the model, "fallback" when generated locally.</param>
public record Explanation(string Summary, IReadOnlyList<string> Suggestions, string Source);

/// <summary>Produces a human-friendly explanation for a computed Framingham result.</summary>
public interface IRiskExplainer
{
    Task<Explanation> ExplainAsync(PatientInput input, RiskResult result, CancellationToken ct = default);
}
